### ISSUE TITLE
配置数据库端口错误

### ISSUE THREAD

**Issue by mokaikai** [bailaohe/parade#1]
没有用完整的uri配置数据库连接，我的配置如下：
```
mysql-conn:
    driver: rdb
    protocol: mysql
    host: 127.0.0.1
    port: 3306
    user: ***
    password: ***
    db: testParade
    # uri: mysql://nameit:changeit@127.0.0.1:3306/yourdb
```
从yaml文件读取port为数字，拼接完整uri时报错，需要改成:
```
mysql-conn:
    driver: rdb
    protocol: mysql
    host: 127.0.0.1
    port: '3306'
    user: ***
    password: ***
    db: testParade
    # uri: mysql://nameit:changeit@127.0.0.1:3306/yourdb
```
